### ISSUE TITLE
Documentation Generic but attractive value proposition for Phlex users

### ISSUE THREAD

**Issue by cancelei** [AliOsm/phlex-icons#25]
I have a complex Phlex setup with DaisyUI via PhlexyUI.

I got only errors following the documentation from the readme file. There is no way to make it work for my case and current technical experience of 3 years.. 

There are different errors that appear depending on little changes of the configuration while following the current conditions of the readme.

![image](https://github.com/user-attachments/assets/34cd7f8f-20ec-4c09-83f3-8174530c8c1f)

Any light? Already spend 3hours trying do implement it.

**Comment by cancelei** [comment]
Other files:
![image](https://github.com/user-attachments/assets/758a48e9-7b73-44b1-b3ee-5f37ef967ee3)


Gemfile
![image](https://github.com/user-attachments/assets/1e17321b-71b0-4458-bf5a-599dddaa6d25)


Usage
![image](https://github.com/user-attachments/assets/9dbcb72a-5b61-4c6f-8d10-adc88c14f7ac)

**Comment by AliOsm** [comment]
Hello @cancelei, sorry I didn't notice the notification. So, you faced this issue while trying to use a custom SVG icon through Phlex::Icons? If yes, what is the Phlex version you are using? If you are using v2, you are correct, there is an issue for custom icons on Phlex v2.

The issue is when you create `Phlex::Icons::Custom` module in `app/components/phlex/icons/custom` directory, this new module will conflict with Phlex itself. So, I need to update the setup for custom icons, but I'm still thinking about it.

**Comment by AliOsm** [comment]
This is not an issue anymore in v2.
Please reopen or create a new issue if you faced other problems.
